services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: database
    volumes:
      - postgres_persist:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "airline" ]
      interval: 10s
      timeout: 5s
      retries: 3

  jwt-user:
    image: jwt-user:v2
    container_name: jwt-user-cont
    depends_on:
      - database

volumes:
  postgres_persist: