spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://database:5432/airline
    driver-class-name: org.postgresql.Driver
  application:
    name: microservice-user-jwt
  cloud:
    vault:
      host: vault-custom
      port: 8200
      scheme: http
      token: ${TOKEN}
      authentication : TOKEN
      kv:
        backend: kv
        default-context: database
        application-name: database
        enabled: true
  config:
    import: vault://
  flyway:
    locations: classpath:/db/migration

server:
  port: 9000

eureka:
  instance:
    instance-id: microservice-user-jwt