drop table if exists entity_user;

create table entity_user (account_no_expired boolean not null,
id bigint generated by default as identity,
email varchar(70) not null unique,
name varchar(70) not null,
password varchar(255) not null,
role smallint check (role between 0 and 1),
account_no_locked boolean not null,
credentials_no_expired boolean not null,
is_enabled boolean not null,
primary key (id))