create table entity_user (id bigint generated by default as identity,
                          email varchar(70) not null unique,
                          name varchar(70) not null,
                          password varchar(255) not null, primary key (id));