CREATE TABLE entity_flight (
id bigint GENERATED BY DEFAULT AS IDENTITY,
air_line VARCHAR (255) CHECK (air_line IN('RENGOKU', 'S_HIGH', 'AEROLINEAS_ARGENTINAS', 'WORLDS', 'ATLANTIC')),
origin VARCHAR (255)CHECK (origin IN('ROSARIO', 'PUEBLA', 'NEW_YORK', 'TOKIO', 'BARCELONA')),
destiny VARCHAR (255) CHECK (destiny IN('ROSARIO', 'PUEBLA', 'NEW_YORK', 'TOKIO', 'BARCELONA')),
price FLOAT(53) NOT NULL,
flight_schedule TIMESTAMP(6),
layover INTEGER NOT NULL,
PRIMARY KEY (id, flight_schedule)) PARTITION BY RANGE (flight_schedule);

CREATE TABLE part_entity_flight_schedule_january_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-01-01') TO ('2024-01-31');
CREATE TABLE part_entity_flight_schedule_february_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-02-01') TO ('2024-02-28');
CREATE TABLE part_entity_flight_schedule_march_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-03-01') TO ('2024-03-31');
CREATE TABLE part_entity_flight_schedule_april_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-04-01') TO ('2024-04-30');
CREATE TABLE part_entity_flight_schedule_may_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-05-01') TO ('2024-05-31');
CREATE TABLE part_entity_flight_schedule_june_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-06-01') TO ('2024-06-30');
CREATE TABLE part_entity_flight_schedule_july_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-07-01') TO ('2024-07-31');
CREATE TABLE part_entity_flight_schedule_august_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-08-01') TO ('2024-08-31');
CREATE TABLE part_entity_flight_schedule_september_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-09-01') TO ('2024-09-30');
CREATE TABLE part_entity_flight_schedule_october_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-10-01') TO ('2024-10-31');
CREATE TABLE part_entity_flight_schedule_november_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-11-01') TO ('2024-11-30');
CREATE TABLE part_entity_flight_schedule_december_2024 PARTITION OF entity_flight FOR VALUES FROM ('2024-12-01') TO ('2024-12-31');
