DROP TABLE entity_hotel;

CREATE TABLE entity_hotel (
id bigint generated BY DEFAULT AS IDENTITY,
name VARCHAR(255),
city VARCHAR(255) CHECK (city IN ('ROSARIO', 'PUEBLA', 'NEW_YORK', 'TOKIO', 'BARCELONA')),
room_type VARCHAR(255) CHECK (room_type IN ('TOURIST','PREMIUM','EXECUTIVE','VIP')),
price_per_night FLOAT(53),
PRIMARY KEY (id, city)) PARTITION BY LIST (city);

CREATE TABLE part_hotel_city_rosario PARTITION OF entity_hotel FOR VALUES IN ('ROSARIO');
CREATE TABLE part_hotel_city_puebla PARTITION OF entity_hotel FOR VALUES IN ('PUEBLA');
CREATE TABLE part_hotel_city_new_york PARTITION OF entity_hotel FOR VALUES IN ('NEW_YORK');
CREATE TABLE part_hotel_city_tokio PARTITION OF entity_hotel FOR VALUES IN ('TOKIO');
CREATE TABLE part_hotel_city_barcelona PARTITION OF entity_hotel FOR VALUES IN ('BARCELONA');